### ISSUE TITLE
Asks for too many Twitter permissions

### ISSUE THREAD

**Issue by joshtriplett** [skade/elixirstatus-web#10]
Attempting to connect a Twitter account asks for permission to:

- Read Tweets from your timeline.
- See who you follow, and follow new people.
- Update your profile.
- Post Tweets for you.

Please document exactly what permissions this actually needs, and how it uses them. And please *don't* ask for permission to "follow new people" or "update your profile", and make "post tweets for you" optional (if there's a feature that actually does that).

**Comment by skade** [comment]
Thanks, that was an oversight.

Changed to lowest level, we only use the authorisation to check you own the twitter account and then throw away the token.

**Comment by joshtriplett** [comment]
@skade Confirmed, and thanks for the lightning-fast response!

**Comment by skade** [comment]
My pleasure! Thanks for the report, that's so easy to miss: almost full permissions are default and you give them during development and are never presented with that screen again :).
