### ISSUE TITLE
Avatars don't show up

### ISSUE THREAD

**Issue by notriddle** [skade/elixirstatus-web#3]
I think elixirstatus has something set up to handle the avatars outside of Phoenix (since there's nothing for `/images/` within `router.ex`).

Do you, @rrrene, know how to set this up?

**Comment by notriddle** [comment]
Okay, in "persistence/user.ex", I found where it downloads the avatars for everybody who posts on ElixirStatus as they log in (`find_or_create`). It drops the file into the static path where it can serve it up.

If you run `heroku logs` while you log in, you'll probably find what the results of the `IO.inspect` on the error are.

**Comment by skade** [comment]
Fixed through #6 and a script.
