### ISSUE TITLE
Shows up as ElixerStatus in feed reader

### ISSUE THREAD

**Issue by casey** [skade/elixirstatus-web#5]
For example:
![screenshot](https://user-images.githubusercontent.com/1945/27410683-eb93b610-569d-11e7-9185-f97cf376dc58.png)

I'm not sure where this is coming from, but it's probably something in the feed XML.

**Comment by skade** [comment]
Thanks for noticing :). I should really work towards proposing some kind of i18n feature for the original app.

**Comment by skade** [comment]
@casey fixed though #7 and an additional fix. Thanks for reporting!

**Comment by notriddle** [comment]
Why isn't this closed?

**Comment by skade** [comment]
Forgotten.

**Comment by casey** [comment]
Sweet! And thanks for this, it's super cool :)
